### ISSUE TITLE
Code for Figure 1

### ISSUE THREAD

**Issue by jrspringman** [DevLab-Duke/mlp-data-intro#3]
@dmoratz we need the code for the Data production workflow. Also, is there a way to take the fancy colors away and just make it black+what?

**Comment by dmoratz** [comment]
This one was a direct copy from the pipeline report- tbh I thought you made this figure! I was struggling to figure out the underlying code, but if you don't know it, I can look more into it

**Comment by jrspringman** [comment]
Well I originally made the figure, but I didn't make the png in the overleaf folder. I've never seen that version with the colored borders. So you (or someone else) exported something to png somehow.

**Comment by dmoratz** [comment]
Fixed
